<?php
// Automatically Generated by TestLink Installer - Mon, 23 Feb 26 19:19:08 +0000
define('DB_TYPE', 'mysql');
define('DB_USER', 'root');
define('DB_PASS', 'root123');
define('DB_HOST', 'db');
define('DB_NAME', 'testlink');
define('DB_TABLE_PREFIX', '');
